retail_analytics:
  target: docker
  outputs:
    docker:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      dbname: analytics
      schema: public
      port: 5432
